include:
  - board: eyelash_sofle_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
  - board: eyelash_sofle_right
    shield: nice_view_custom
    snippet: studio-rpc-usb-uart
  - board: eyelash_sofle_left
    shield: settings_reset
